Mo/testing train
osswald/dvzo pull request #16
Opened 2021-02-13 21:23 UTC by busykoala

2021-02-13 21:40 UTC, busykoala commented
Not to be applied.

2021-02-14 16:07 UTC, osswald commented on train_management/templates/train_management/day_planning_list.html
> +<button id="button" class="btn btn-secondary">getSelections</button>
make label of button translatable
also, since the button doesn't really do anything yet, please deactivate it for the moment

2021-02-14 16:09 UTC, osswald commented on train_management/views.py
> +            # current_vehicles = "<span class="badge bg-success\">Peter</span>"
remove line

2021-02-14 16:12 UTC, osswald requested changes
have a look at my comments

2021-02-17 14:38 UTC, merged