Work on briefing pdf
osswald/dvzo pull request #85
Opened 2021-05-08 20:56 UTC by haustre

* Add i18n to jinja2
* Move briefing_pdf from pdf.py to dayplanning.py
* Use the samle dayplanning_context in html and pdf

2021-05-13 12:40 UTC, busykoala approved these changes
Merci, sieht gut aus! :smiling_face_with_three_hearts:

2021-05-13 15:16 UTC, osswald requested changes

2021-05-13 15:16 UTC, osswald commented on train_management/templates/latex/briefing.tex
> +      \hline Einsatzort & Funktion & Name & Telefon \\
please use l10n

2021-05-13 15:16 UTC, osswald commented on train_management/templates/latex/briefing.tex
> +  \textbf{Personal}
please use l10n

2021-05-30 16:32 UTC, closed without merging

2021-05-30 16:33 UTC, osswald commented
will not be used